wandb_version: 1

out_dir:
  desc: null
  value: out-wikipedia-shards
eval_interval:
  desc: null
  value: 10
log_interval:
  desc: null
  value: 1
eval_iters:
  desc: null
  value: 100
eval_only:
  desc: null
  value: false
always_save_checkpoint:
  desc: null
  value: true
init_from:
  desc: null
  value: resume
wandb_log:
  desc: null
  value: true
wandb_project:
  desc: null
  value: wikipedia-shards
wandb_run_name:
  desc: null
  value: run1703148616.9883318
dataset:
  desc: null
  value: sorted_wikipedia_dataset
gradient_accumulation_steps:
  desc: null
  value: 1
batch_size:
  desc: null
  value: 8
block_size:
  desc: null
  value: 256
n_layer:
  desc: null
  value: 6
n_head:
  desc: null
  value: 6
n_embd:
  desc: null
  value: 384
dropout:
  desc: null
  value: 0.2
bias:
  desc: null
  value: false
learning_rate:
  desc: null
  value: 0.001
max_iters:
  desc: null
  value: 5000
weight_decay:
  desc: null
  value: 0.1
beta1:
  desc: null
  value: 0.9
beta2:
  desc: null
  value: 0.99
grad_clip:
  desc: null
  value: 1.0
decay_lr:
  desc: null
  value: true
warmup_iters:
  desc: null
  value: 1
lr_decay_iters:
  desc: null
  value: 5000
min_lr:
  desc: null
  value: 0.0001
backend:
  desc: null
  value: nccl
device:
  desc: null
  value: cuda
dtype:
  desc: null
  value: float16
compile:
  desc: null
  value: true
_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.16.0
    framework: huggingface
    huggingface_version: 4.35.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1703148620.233362
    t:
      1:
      - 1
      - 11
      - 49
      - 55
      - 105
      2:
      - 1
      - 11
      - 49
      - 55
      - 105
      3:
      - 13
      - 16
      - 23
      4: 3.11.5
      5: 0.16.0
      6: 4.35.2
      8:
      - 5
      13: linux-x86_64
